baseURL = "https://adityakadali.netlify.app/"
languageCode = "en-us"
title = "Aditya"
theme="archie"
copyright = "© Aditya"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A Personal blog page for my self reflection"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/adityakadali"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/adityakadali/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4