baseURL = "https://adityakadali.netlify.app/"
languageCode = "en-us"
title = "Aditya"
theme="archie"
copyright = "© Aditya"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=4 # articles per page


[params]
	favicon = "https://raw.githubusercontent.com/Adityakadali/My-site/master/resources/_gen/images/favicon.ico"
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A Personal blog page for my self reflection"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/adityakadali"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/adityakadali/"

# [[params.social]]
# name = "Instagram"
# icon = "instagram"
# url = "https://gitlab.com/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 4

[permalinks]
  # posts = "/posts/:year/:month/:title/"
  posts = "/posts/:title/"

[author]
  name = "Aditya Kadali"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"